[package]
edition = "2021"
license = "GPL-3.0"
name = "desktop_proxy"
version = "0.0.0"

[dependencies]
anyhow = "1.0"
desktop_core = { path = "../core" }
env_logger = "0.10.0"
log = "0.4.17"
parity-tokio-ipc = "0.9.0"
tokio = { version = "1.23.0", features = ["full"] }
