# Runs on creation of new Pull Requests
# If the source branch starts with /feature, add a needs-qa label
---

name: Label Feature Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'feature/**'

jobs:
  add-needs-qa-label:
    name: Add label to pull request
    uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
    with:
      add-labels: `needs-qa`