---
name: QA - Web Release

on:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-20.04
    steps:
      - name: Branch check
        run: |
          if [[ "$GITHUB_REF" != "refs/heads/DEVOPS-843_qa_web_vault_to_cloudflare" ]] && [[ "$GITHUB_REF" != "refs/heads/master" ]] && [[ "$GITHUB_REF" != "refs/heads/rc" ]] && [[ $GITHUB_REF != refs/heads/hotfix-rc/* ]]; then
            echo "==================================="
            echo "[!] Can only release from the 'master', 'rc' or 'hotfix-rc/*' branches"
            echo "==================================="
            exit 1
          fi

  cfpages-deploy:
    name: Deploy Web Vault to QA CloudFlare Pages branch
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2

      - name: Download latest cloud asset
        uses: bitwarden/gh-actions/download-artifacts@c1fa8e09871a860862d6bbe36184b06d2c7e35a8
        with:
          workflow: build-web.yml
          path: apps/web
          workflow_conclusion: success
          branch: ${{ github.ref_name }}
          artifacts: web-*-cloud-COMMERCIAL.zip

      # This should result in a build directory in the current working directory
      - name: Unzip build asset
        working-directory: apps/web
        run: unzip web-*-cloud-COMMERCIAL.zip

      - name: Checkout Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2
        with:
          ref: cf-pages-qa
          path: deployment

      - name: Setup git config
        run: |
          git config --global user.name = "GitHub Action Bot"
          git config --global user.email = "<>"
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
          git config --global url."https://".insteadOf ssh://

      - name: Deploy CloudFlare Pages
        run: |
          rm -rf ./*
          cp -R ../apps/web/build/* .
        working-directory: deployment

      - name: Create cf-pages-qa-deploy branch
        run: |
          git switch -c cf-pages-qa-deploy-${{ github.ref_name }}
          git add .
          git commit -m "Staging deploy ${{ github.ref_name }}"
          git push -u origin cf-pages-qa-deploy-${{ github.ref_name }}
        working-directory: deployment

      - name: Create CloudFlare Pages Deploy PR
        if: ${{ github.event.inputs.release_type != 'Dry Run' }}
        env:
          PR_BRANCH: cf-pages-qa-deploy-${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Deploy ${{ github.ref_name }} to CloudFlare Pages" \
            --body "Deploying ${{ github.ref_name }}" \
            --base cf-pages-qa \
            --head "$PR_BRANCH"
