# Assign reviewer based on PR labels
#
# Only runs for PRs opened by Renovate bot
---
name: Renovate reviewer assigner

on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'

jobs:
  reviewer-assigner:
    if: github.actor == 'renovate[bot]'
    runs-on: ubuntu-22.04
    steps:
      - name: "Assign reviewer"
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            // Get list of labels
            const labels = context.payload.pull_request.labels
              .map(label => label.name)
              .filter(label => label.startsWith('team:'));

            const reviewers = labels.map(label => {
              const team = label.split(':')[1];
              return 'team-' + team + '-dev';
            });

            // Assign reviewers
            await github.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              team_reviewers: reviewers,
            });
